### ISSUE TITLE
Today on November 1st, it is showing November 11th.

### ISSUE THREAD

**Issue by jacobrillema** [rid9/DateTime#2]
Today on November 1st, it is showing November 11th. Time is correct but not the date, seems really odd.

**Comment by rid9** [comment]
@jacobrillema, sorry, can't reproduce the issue. I tried hardcoding the date of November 1, and as far as I can see, it shows November 1, not 11. Can you please try reproducing again and let me know what to change in order to see the problem, as well as what `dateTime.*` settings you're using? You can edit `~/.vscode/extensions/rid9.datetime-1.0.5/out` and restart Visual Studio Code after each edit if you'd like to change the code.

**Comment by jacobrillema** [comment]
Hi there, I apologize for the late response back. It was an operator error on my configuration settings. Sorry for the confusion and thank you for a nice extension to use with VS Code.

**Comment by shankarramr** [comment]
Mine is stuck at April 4 2018. That's the date I installed the plugin I believe. As said above, the time runs correct but the date doesn't change.

**Comment by rid9** [comment]
@shankarramr, can you please post your configuration, if any?

**Comment by shankarramr** [comment]
Do you mean user settings I have configured for this plugin?
If so, then just this: "dateTime.customFormat": "dddd, MMMM Mo, YYYY HH:MM:ss"

**Comment by rid9** [comment]
@shankarramr, I see, shouldn't that be "dddd, MMMM Do, YYYY HH:MM:ss" though? M (the month) is April (the 4th), whereas D (the day) is now 9.

**Comment by shankarramr** [comment]
Oops, my bad... I was being lazy there. I just blindly combined the two entries from the Example usage documentation into one line (without actually reading the commented result above it).
Thanks! It works now.

**Comment by rid9** [comment]
@shankarramr, no problem, glad it works.
