### ISSUE TITLE
Feature request, simple insert

### ISSUE THREAD

**Issue by darrylhebbes** [rid9/DateTime#23]
Hi,

A simple request to insert the date at the active cursor if the date area is clicked in the activity bar.

Thanks

**Comment by tg-courses** [comment]
@darrylhebbes, clicking the date area currently copies the date and time to the clipboard as they are displayed. You can also format how the date and time are copied with the `dateTime.clipboardFormat` configuration option.

The closest thing would therefore be clicking then pasting instead of just clicking. Does this cover what you needed the feature for?

**Comment by rid9** [comment]
@darrylhebbes, clicking the date area currently copies the date and time to the clipboard as they are displayed. You can also format how the date and time are copied with the `dateTime.clipboardFormat` configuration option.

The closest thing would therefore be clicking then pasting instead of just clicking. Does this cover what you needed the feature for?

**Comment by darrylhebbes** [comment]
Hi, Thanks, long forgot about this request. I moved away from VsCode, was always an Emacs user since 2002, so just wrote the feature I needed in Elisp.Thanks for the reply Darryl On 7. Aug 2024, at 23:05, rid9 ***@***.***> wrote:﻿
@darrylhebbes, clicking the date area currently copies the date and time to the clipboard as they are displayed. You can also format how the date and time are copied with the dateTime.clipboardFormat configuration option.
The closest thing would therefore be clicking then pasting instead of just clicking. Does this cover what you needed the feature for?
