### ISSUE TITLE
Feature Request : clock status bar priority

### ISSUE THREAD

**Issue by hucuyuu** [rid9/DateTime#9]
Awesome extension!

This is the only extension that I found supports locale.

I would appreciate if you could add a feature that could change the clock status bar priority. So that I could change where the clock shows on my status bar.

![123](https://user-images.githubusercontent.com/22560245/106284709-80b9e580-627e-11eb-9333-f8192099f583.png)

**Comment by rid9** [comment]
Thank you for the suggestion.

The latest version of the extension has two additional configuration options:

- `statusBarAlignment` which can be `left` or `right` (defaults to `right`).
- `statusBarPriority` which is a number (defaults to 100,000 to the left when the alignment is `left`, or to the right otherwise).
